# favicon path to your logo
favicon:

# whether to display `CC BY-SA 4.0` declaration
declaration: true

# personal links
## links icon base folder
linkiconbase: /images/links/
## array of links
links:
  - name:
    link:
    icon:

# comment
waline:
  enabled: true
  serverURL:
  placeholder:
  avatar:
  emoji:
    bilibili: true
    qq: true
    tieba: true
    twitter: true
    alus: true
    weibo: true

# pagination
pagination:
  prev_text: '<'
  next_text: '>'

# footer
## for users in China
icp:
## visitor counter
counter:
  enabled: true
  ### refer to https://github.com/syy11cn/hexo-theme-linear/blob/main/docs/guide.md
  url:
