# favicon
favicon:

# license of articles
declaration: true

# personal links
linkiconbase: /images/links/
links:
  - name: github
    link: https://github.com/syy11cn
    icon: github.png
  - name: twitter
    link: https://twitter.com/syy11cn
    icon: twitter.png
  - name: email
    link: 'mailto:syy11cn@outlook.com'
    icon: email.png
  - name: rss
    link: /atom.xml
    icon: feed.png
  - name: links
    link: /links/
    icon: friends.png

# comment
valine:
  enabled: true
  appId:
  appKey:
  placeholder: 欢迎你的评论~

# footer
icp: ''
counter:
  enabled: true
  url: https://www.mfwztj.com/hit.php?id=zemuxkao&nd=6&style=1
