# favicon path to your logo
favicon:

# whether to display `CC BY-SA 4.0` declaration
declaration: true

# personal links
## links icon base folder
linkiconbase: /images/links/
## array of links
links:
  - name:
    link:
    icon:

# comment
valine:
  enabled: true
  appId:
  appKey:
  placeholder:
  avatar:

# footer
## for users in China
icp:
## visitor counter
counter:
  enabled: true
  ### refer to https://github.com/syy11cn/hexo-theme-linear/blob/main/docs/guide.md
  url:
